linuxdeepin/dde-launcher

- src/windowedframe.cpp
dock在右边时，启动launcher会看到launcher没有贴近dock。
launcher的右边是根据字号来计算宽度的，所以需要调用adjustSize先计算一下。
> fix(Window): When the dock is on the right, the position is not close

- src/fullscreenframe.cpp
在sw平台启动后，内容在进行大小调整的时候会看到上下快速移动。
> fix: will flash on the sw platform

- src/model/appsmanager.cpp
qSort is deprecated. Use std::sort instead.
> fix: qSort deprecation warnings

- .packit.yaml
- rpm/dde-launcher.spec
This commit contains the specfile for building the official package for Fedora
with a Packit setup.
Ultimately, a unified specfile is targeted for Fedora and any other rpm-based
distributions, e.g. openEuler.
And Packit(https://packit.dev/) is a tool for maintaining specfile within
upstream source. It requires a simple config file(.packit.yaml).
Log:
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>
> feat: Initial packit setup

- archlinux/PKGBUILD
Support the mode that use the workspace wallpaper, and further, it should also support the transparent mode.
Note that this submission will not reduce memory pressure, only the interface effect.
Log:
Issue: Closes linuxdeepin/developer-center#2588
> feat: add use-workspace-background gsetting

- src/windowedframe.cpp
- src/windowedframe.h
启动器的位置跟随 dock 的位置，那么就应该根据
dock 的 geometrychanged 来修正自己的位置，dock
的接口如果返回错误那么 dock 中修改，而不是在
启动器中去矫正。
Log:
Bug: https://pms.uniontech.com/bug-view-127439.html
Influence: wayland + 缩放多屏 + 启动器位置
Change-Id: Id794c68a916283f223cf23d8991e5d8a7dc76091
> fix: 仅HDMI屏拔掉HDMI显示屏，启动器位置显示异常

- src/windowedframe.cpp
第一次弹出菜单时会将界面设置为ApplicationDeactivate状态，再次弹出菜单时会隐藏界面
因此需要隐藏界面时判断下是否是弹出菜单导致的ApplicationDeactivate状态
否则不隐藏
Log: 修复wayland下多次右键弹出菜单时界面自动隐藏的问题
Bug: https://pms.uniontech.com/bug-view-150143.html
Influence: wayland下多次右键菜单时界面不会自动隐藏
Change-Id: Idebacba1782d075d7168a31dd5234235c4a1242b
> fix: 修复wayland下多次右键菜单时界面自动隐藏的问题

- src/fullscreenframe.cpp
- src/fullscreenframe.h
- src/model/appslistmodel.cpp
- src/model/appslistmodel.h
- src/view/applistview.cpp
- src/view/applistview.h
- src/windowedframe.cpp
- src/worker/menudialog.cpp
- src/worker/menudialog.h
- src/worker/menuworker.cpp
- src/worker/menuworker.h
当右键菜单出来后，左边的选中项在鼠标再移动过去的时候不再变化
直到菜单消失后，鼠标选中效果才出现
Log: 启动器选中效果变更
Influence: 右键菜单
Bug: https://pms.uniontech.com/bug-view-152801.html
Change-Id: I994c11b7c836a140331ab349f12bccdd5dbd20e1
> fix: 处理启动器右键选中效果的交互逻辑

- src/worker/menudialog.cpp
将菜单界面设置为Popup类型，修复圆角不生效问题
Log: 修复在启动器中选中应用并鼠标右键，显示窗口为直角问题
Bug: https://pms.uniontech.com/bug-view-152599.html
Influence: 应用右键菜单显示圆角
> fix: 设置菜单界面类型为Popup修复菜单圆角问题

- debian/control
更新依赖描述（`libxcb-util0` -> `libxcb-util1`），使可以在新版 debian 中顺利构建。（注：在 v20 停止支持后，可考虑移除 libxcb-util0 依赖）
是处理 https://github.com/linuxdeepin/developer-center/issues/3230 问题的一部分。
> chore: build on newer debian release

- src/windowedframe.cpp
未显示应用菜单时，鼠标移出列表区域，取消应用选中状态;
显示应用菜单时，移动鼠标菜单保持显示并且左侧图标不显示选中状态。
Log: 修复窗口模式下同时显示两个选中状态问题
Bug: https://pms.uniontech.com/bug-view-154851.html
Influence: 应用选择中状态优化
> fix: 应用选中状态优化

- src/view/applistview.cpp
- src/view/applistview.h
- src/widgets/smoothscrollbar.cpp
- src/widgets/smoothscrollbar.h
滚动事件每触发一次就会导致上次未结束的动画提前结束，导致滚动距离达不到预期目标，滚 轮滚动越快，列表滚动越慢 ，本次提交引入了一个平滑滚动条控件，替换了原有的滚动动画方案，解决了此问题。
> fix: 修复小窗模式下滚动动画被连续打断的问题

- src/boxframe/backgroundmanager.cpp
判断条件错误导致屏幕名称获取异常
Log:
Influence: 启动器-全屏壁纸跟随桌面壁纸更新
Bug: https://pms.uniontech.com/zentao/bug-view-113571.html
> fix: 修复启动器全屏壁纸不跟随桌面更新的问题

- src/fullscreenframe.cpp
- src/windowedframe.cpp
有搜索内容，且有搜索结果，默认选中第一项；
非搜索状态，或搜索框文本为空时，不选中任何项；
Log: 调整交互
Task: https://pms.uniontech.com/story-view-23419.html
> fix: 调整搜索状态下的交互

- src/windowedframe.cpp
Log: DLineEdit
Bug: https://pms.uniontech.com/bug-view-155411.html
Influence: search
> fix: cannot focus when input text with ime

- src/widgets/miniframebutton.cpp
- src/widgets/miniframebutton.h
we shouldn't save a pixmap for svg in mutli scale factor scene.
it call QIcon's paint() to paint in device instead of QPainter's drawPixmap(), otherwise, we need to deal with some details， for example deviceRatio.
if we need to draw some shape to the center of QPainter, we can
call moveCenter(), it is equal to QPoint of
(width / 2 + 1, height / 2 + 1).
Log: 在高缩放比例下，启动器侧边按钮模糊
Bug: https://pms.uniontech.com/bug-view-148759.html
Influence: 在高缩放比例下，启动器侧边按钮模糊
Change-Id: I8786fec0d0537989dee0f3d594196f2004b819fb
> fix: RightBarButton blur in high scale factor

- src/windowedframe.cpp
按UI设计，搜索输入框允许显示激活样式
Log: 修复小窗口搜索框缺少激活样式问题
Bug: https://pms.uniontech.com/bug-view-164813.html
Influence: 小窗口搜索框允许显示激活样式
> fix: 设置搜索输入框允许显示激活样式

- src/fullscreenframe.cpp
已与产品确认，改为与窗口模式一样，删除所有搜索字符后，搜索框保持有光标
Log: 修复启动器全屏模式搜索框删除输入的所有字符,输入光标消失的问题
Bug: https://pms.uniontech.com/bug-view-163537.html
Influence: 启动器
Change-Id: I0c3d81966e929c345b859d359f5408c436d51645
> fix: 修复启动器全屏模式搜索框删除输入的所有字符,输入光标消失的问题

- src/view/multipagesview.cpp
原本逻辑当搜索结果页面大于两页时候，逻辑中触发了两次launchapp,
第一次会发送空的modelindex, 清空搜索框，
第二次在原来坐标上触发按钮事件，
这里暂时把逻辑注释，
Log: 搜索
Bugs: https://github.com/linuxdeepin/developer-center/issues/3418
-------
Resolve https://github.com/linuxdeepin/developer-center/issues/3418
> fix: search and launch app

- .gitignore
- src/fullscreenframe.cpp
- src/windowedframe.cpp
按设计要求，文案“确定”应该为卸载，表达意思更明确
Log: 修复卸载弹窗危险操作没有使用红色的警示按钮的问题
Bug: https://pms.uniontech.com/bug-view-167547.html
Influence: 卸载文案
Change-Id: I340a2b840fc686ebff5c178c3e31134eeecbdb08
> fix: 修复卸载弹窗危险操作没有使用红色的警示按钮的问题

- CMakeLists.txt
Append to CMAKE_EXE_LINKER_FLAGS instead of overriding them.
Log: Don't ignore CMAKE_EXE_LINKER_FLAGS specified by system
> fix: don't ignore CMAKE_EXE_LINKER_FLAGS specified by system

- src/delegate/applistdelegate.cpp
绘制打印驱动时，未获取到图标
Log: 解决打印驱动安装后没有图标的问题
Influence: 安装打印驱动
Bug: https://pms.uniontech.com/bug-view-163925.html
> fix: 打印驱动安装后启动器没有图标

- src/delegate/applistdelegate.cpp
修正小窗口启动器下，分类标题的文字大小与颜色不正确的问题
Resolve https://github.com/linuxdeepin/developer-center/issues/3641
> fix(UI): incorrect category text size and color in windowed frame

- src/delegate/appitemdelegate.cpp
应用分组最多应当显示不超过四个图标。
Resolve https://github.com/linuxdeepin/dde-launcher/issues/342
> fix(UI): app group should show max to 4 icons

- src/widgets/appdrawerwidget.cpp
尽可能避免硬编码尺寸到屏幕大小，AppDrawerWidget 的尺寸本身已取决于其 parent 控件的尺寸。
> chore: avoid hardcode size to screen rect

- src/widgets/appdrawerwidget.cpp
- src/widgets/appdrawerwidget.h
修复不正确的 DBlurEffect 用法，导致 Launcher 全屏抽屉背景模糊无效的问题
Resolve https://github.com/linuxdeepin/dde-launcher/issues/350
> fix: incorrect usage of DBlurEffect

- src/delegate/appitemdelegate.cpp
修复抽屉图标组中的图标没有对齐的问题
Resolve https://github.com/linuxdeepin/developer-center/issues/3864
由 @vivianxf 发现的问题。
> fix: icons insider drawer group icon not aligned up

- src/model/appsmanager.cpp
- src/model/appsmanager.h
使用 m_trashItemInfo 对象用于直接更新trash图标变化,
而不是发送全部更新的信号
fix https://github.com/linuxdeepin/developer-center/issues/3778
> fix: 当回收站发生变化时,调整只更新trash图标

- src/boxframe/boxframe.cpp
It's crased when screenIndex is out of the Array bounds.
> fix: Crashed in some scene

- src/main.cpp
在 QCoreApplication 创建前设置 Qt::AA_EnableHighDpiScaling。
Log:
> chore: set Qt::AA_EnableHighDpiScaling before QCoreApplication created

- src/fullscreenframe.cpp
- src/model/appslistmodel.cpp
- src/model/appslistmodel.h
- src/view/appgridview.cpp
- src/view/multipagesview.cpp
- src/windowedframe.cpp
- src/windowedframe.h
当收藏的应用不多于 4 个时，仅展示一行高度的收藏区域。
Resolve https://github.com/linuxdeepin/dde-launcher/issues/380
> fix(WindowedFrame): show one row when fav <= 4

- .tx/config
- debian/changelog
Changelog
* Make use of Qt CMake module to find package
* Correct category text size and color in windowed frame
* App group should show max to 4 icons in fullscreen frame
* Fix window mode load slow caused by icon reload
* avoid hardcode size to screen rect
* Fix missing blur in the app drawer of fullscreen frame
* Fix icons inside app drawer not aligned up
* Fix mode switch button icon size caused blurry icon
* Show one favorate row when favorate apps are less than 5
> chore: bump version to 6.0.9

- src/widgets/modeswitch.cpp
1. 没有设置 iconsize ,这样缩放后可能导致图标太大
2. 换成直接将由 svg 文件构造QIcon, 此时使用的是 SvgIconEngine 图标清晰
Issue: https://github.com/linuxdeepin/developer-center/issues/4110
> fix: 应用分类图标显示不清晰

- src/windowedframe.cpp
当获取 dde-dock 位置的 dbus 无法返回正确信息时，不尝试将 launcher
移动到无效的位置。
> fix: avoid moving window to the void when dock dbus is missing

- src/main.cpp
提高位图缓存，避免在较高分辨率下 pixmap cache 不够大，由图标重绘产生卡顿。
> chore: raise up the pixmap cache limit to 64800 KiB

- debian/changelog
Changelog:
* Avoid setting invalid font weight to QFont
* Avoid moving window to invalid place when certain dbus is missing
* Raise up pixmap cache limit to 64800 KiB
* Fix duplicate icons may be shown after update launcher
> chore: release 6.0.11

- src/model/appsmanager.cpp
从m_allAppInfoList更新数据时，应该同时检查该应用是否已经被拖到文件夹中。
如果已在文件夹中，不会在m_fullscreenUsedSortedList直接检索到，此时不应该添加该数据。
> fix: icons will be added repeatedly

- CMakeLists.txt
- debian/control
- src/model/appslistmodel.cpp
- src/model/appsmanager.cpp
- src/model/appsmanager.h
- src/trashutils/trashmonitor.cpp
- src/trashutils/trashmonitor.h
The old implementation only monitor the trash folder in user's partition, thus the trash folder in other partition will not trached. It will cause the launcher icon status out-of-sync with the real trash status.
This patch switch to use gio to monitor the trash status (might need to port to dtkio when it get a stable release).
Issue: https://github.com/linuxdeepin/developer-center/issues/4478
Log: Fix the trash icon status might out-of-sync in some cases
> fix: incorrect trash status when deleting file in other partition

- CMakeLists.txt
use DtkTools and DTK_XML2CPP var instead of qdbusxml2cpp-fix binary direct
log:
> fix: qdbusxml2cpp-fix not generate cpp code after dtkcore update

- debian/changelog
Changelog:
* Avoid display multiple entries for desktop files shares the same freedesktop id
* Fix incorrect trash icon status when there are trashed files in partitions other than home https://github.com/linuxdeepin/developer-center/issues/4478
* Avoid hardcode dde-launcher binary path
* Use qdbusxml2cpp-fix path provided by DtkTools CMake module
Log:
> chore: release dde-launcher 6.0.14

- src/delegate/appitemdelegate.cpp
屏蔽拖放添加黑框暂时解决问题。拖放悬停画黑框的功能实现有误。
Bug: https://github.com/linuxdeepin/developer-center/issues/3993
Log: 修复拖放图标改变位置导致出现黑框
> fix: 修复拖放图标改变位置导致出现黑框

- src/boxframe/backgroundmanager.cpp
launcher background use desktop wallpaper, should associate "allwallpaperuris" type
Log: fix the problem that the background image did not follow the change when switching the theme
Resolve: https://github.com/linuxdeepin/developer-center/issues/3663
> fix: onAppearanceChanged use mistake type

- src/model/appsmanager.cpp
removeDuplicateData should not sort app list again just remove duplicated app(desktop)
Issue: https://github.com/linuxdeepin/developer-center/issues/5085
> fix: move and sort app failed

- src/dbusinterface/aminterface.h
initialize member value of class AmInterface explicitly
Log: initialize member value explicitly
> chore: initialize member value explicitly

- src/dbusinterface/aminterface.cpp
when desktop path is symLink, uninstall failed.
Should use desktop name instead of dekstop path.
Log: uninstall failed
> fix: uninstall failed

- src/model/appslistmodel.cpp
- src/model/appsmanager.cpp
- src/model/appsmanager.h
- src/view/appgridview.cpp
- src/windowedframe.cpp
- src/worker/menuworker.cpp
1. remove unused headers and members;
2. rename member functions;
3. change public interfaces to private interfaces;
Log: clean code on appsmanager
> refact: clean code on appsmanager

- src/launchersys.cpp
RegionMonitorPoint will list all forign windows and test if mouse is clicked 'onboard'
> chore: not test mouse point if launcher is hidden

- debian/changelog
此 tag release 旨在解决技术预览插件无法从 launchpad 切换回 launcher 的问题。
涉及两个 Issue：
- https://github.com/linuxdeepin/developer-center/issues/5330 
- （对应集成 https://github.com/linuxdeepin/developer-center/issues/6527 ）
- https://github.com/linuxdeepin/developer-center/issues/6516
- （关联集成 https://github.com/linuxdeepin/developer-center/issues/6538 ）
> chore: release dde-launcher 6.0.19
