src/fullscreenframe.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1395

fix(FullScreen): category list coordinate error

---

src/windowedframe.cpp

fix(Mini): unable to launch app in category list search

---

src/model/appslistmodel.cpp

src/model/appslistmodel.cpp:L61
add  deepin-terminal

forbiden uninstall deepin-terminal

---

src/launchersys.cpp

启动时根据后端记录的模式来初始化对应的launcher，减少不必要的初始化

optimize: initalize only the required initators at startup

---

src/delegate/applistdelegate.cpp
src/global_util/calculate_util.cpp

fix: applist icon size

---

.github/workflows/build.yaml

fix: github action

---

.github/workflows/build.yaml
src/widgets/modetogglebutton.cpp
src/windowedframe.cpp

missing QPainterPath header
Log:

fix: missing QPainterPath header

---

src/windowedframe.h

上个提交漏掉了头文件修改的提交，再次补上
Log:
Influence: build
Change-Id: I493013e9be46d8b40ed3ce38030c9ab01fab11c5

fix(build): no declaration matches onDockGeometryChanged

---

debian/changelog

修改changelog内容，修复编译失败问题
Log: 修复编译失败问题
Task: https://pms.uniontech.com/task-view-174659.html
Influence: 正常编译

fix: 修复github编译失败问题

---

src/fullscreenframe.cpp
src/model/appslistmodel.cpp
src/model/appslistmodel.h
src/windowedframe.cpp
src/windowedframe.h
src/worker/menuworker.cpp
src/worker/menuworker.h

右键点击启动器效果消失优化成不消失
其他项被选中，则立即取消右键菜单
Log: 窗口模式右键点击效果优化
Influence: 启动器右键点击
Change-Id: I8bccb21468f9417845f51ad5d8b0b23b5eabf93d

feat: 右键点击选中效果消失优化

---

src/windowedframe.cpp

启动器搜索右键效果优化
Log: 启动器搜索右键效果优化
Influence: 启动器搜索
Bug: https://pms.uniontech.com/bug-view-152801.html
Change-Id: I8f81ebe3ddb2e7cd197f55c4390bf99aa480973a

fix: 启动器搜索右键效果优化

---

src/model/appsmanager.cpp
src/model/iconcachemanager.cpp

community version has qt patch
Log:

fix: window mode show slowly

---

src/windowedframe.cpp
src/windowedframe.h

优化冷启动速度
Log: 优化冷启动速度
Influence:
Bug: https://pms.uniontech.com/task-view-216137.html

fix: 优化冷启动速度

---

CMakeLists.txt
plugins/appsearch/CMakeLists.txt
src/global_util/util.cpp
src/model/appsmanager.cpp
src/view/applistview.cpp

chore(cmake): use modern way to find package

---

src/global_util/util.cpp
src/global_util/util.h
src/model/appsmanager.cpp

修复图标加载导致的窗口模式打开缓慢问题。
Related: https://github.com/linuxdeepin/dde-launcher/pull/333

fix: window mode load slow caused by icon reload

---

tests/global_util_unit_test/ut_calculate_util.cpp

Correct a typo in ut_calculate_util.cpp

chore: correct a typo in ut_calculate_util.cpp

---

src/main.cpp
src/sharedeventfilter.cpp

startDetached not use desprate style

---

src/widgets/modeswitch.cpp

Closed: https://github.com/linuxdeepin/dde-launcher/issues/352

fix: mode switch button icon size

---

src/view/multipagesview.cpp

delta is deprecated, so use angleDelta instead
Log: handle deprecated function

chore: use angleDelta not delta

---

debian/changelog

Changelog
* Update documentation
* Fix application blurry category icon issue https://github.com/linuxdeepin/dde-launcher/pull/388

chore: release 6.0.10

---

src/widgets/searchmodewidget.cpp
src/windowedframe.cpp

QFont 字重的范围是 0~99，超出此范围的值实际无效。

fix: avoid set invalid font weight to QFont

---

src/model/appsmanager.cpp
src/model/appsmanager.h

remove duplicate item which in fullscreen and window list.
Log:

fix: duplicate icons in menu after update launcher

---

src/model/appsmanager.cpp
src/model/appsmanager.h

We should also update the data from m_allAppInfoList which is not existed in m_fullscreenUsedSortedList.
Log:
close linuxdeepin/developer-center#4285

fix: icons are not displayed in fullscreen mode

---

debian/changelog

Changelog:
* Fix new icons might not displayed in fullscreen mode (https://github.com/linuxdeepin/dde-launcher/pull/396) (https://github.com/linuxdeepin/developer-center/issues/4285)

chore: release 6.0.12

---

debian/changelog

Changelog:
* fix icons will be added repeatedly
Log:

chore: release 6.0.13

---

src/model/appsmanager.cpp

The example of icon duplicate:
1. Make a soft link of any desktop to other path which in XDG_DATA_DIRS.
2. Install the same package in diffrent formats.
close linuxdeepin/developer-center#4374

fix: the same desktop is also considered duplicate

---

.reuse/dep5
CMakeLists.txt
dde-launcher-wapper
dde-launcher-wapper.in
dde-launcher.desktop
src/dbusservices/org.deepin.dde.Launcher1.service
src/dbusservices/org.deepin.dde.Launcher1.service.in

feat: avoid use hardcode path

---

src/model/appsmanager.cpp

check if iterator is valid when erasing it.
Log: crashed when starting

fix: crashed when starting

---

src/model/appsmanager.cpp

chore: correct a typo in appsmanager.cpp

---

debian/changelog

version 6.0.16 (old AM)
Log: update changelog 6.0.16 (old AM)

chore: update changelog (old AM)

---

src/dbusinterface/aminterface.cpp
src/dbusinterface/aminterface.h
src/global_util/calculate_util.cpp
src/launchersys.cpp
src/model/appsmanager.cpp
src/model/appsmanager.h
src/widgets/searchwidget.cpp
src/windowedframe.cpp
src/worker/menuworker.cpp

adapt to AM_Reborn about fullscreen & window
Issue: https://github.com/linuxdeepin/developer-center/issues/5519

fix: switch between fullscreen & window

---

src/dbusinterface/aminterface.cpp
src/dbusinterface/aminterface.h
src/model/appsmanager.cpp

check the field NoDisplay
Issue: https://github.com/linuxdeepin/developer-center/issues/5513

fix: application with no icon

---

src/dbusinterface/aminterface.cpp
src/dbusinterface/aminterface.h

abandon the solution that monitors files.
connect the signal of autostart property changed.
Log: connect autostartchanged signal

chore: connect autostartchanged signal

---

src/model/appsmanager.cpp

adjust removeDuplicateData to adapt to new AM
Log: adjust removeDuplicateData

chore: adjust removeDuplicateData

---

CMakeLists.txt
src/dbusinterface/aminterface.cpp
src/dbusinterface/aminterface.h

change the calling parameter to desktop from id
Log: uninstall apps failed

fix: uninstall apps failed

---

src/model/appsmanager.cpp

不仅移除 XDG_DATA_DIRS 中的其他 desktop
还要移除相同的 item （怎么混进来的 ？
修复 erase 只移除了一个 iterator 的问题
processList.erase(it, processList.end());
Issue: https://github.com/linuxdeepin/developer-center/issues/4374

fix: duplicated item show in launcher

---

src/model/appsmanager.cpp
src/model/appsmanager.h

1. rename function
2. remove unused member
3. move function
Log: optimize code on appsmanager

refact: optimize code on appsmanager

---

src/dbusinterface/dbusvariant/iteminfo.cpp
src/dbusinterface/dbusvariant/iteminfo.h
src/model/appsmanager.cpp
src/model/appsmanager.h

move conversion between SettingsMap and ItemInfo_v1 to ItemInfo_v1
Log: optimize code on SettingsMaptoItemInfoList

refact: optimize code on SettingsMaptoItemInfoList

---

misc/CMakeLists.txt

fix: logout timeout
